//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RB90
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://me.rb90/mup/", ConfigurationName="RB90.mup")]
    public interface mup
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/addPerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RB90.addPersonResponse addPerson(RB90.addPersonRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/addPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<RB90.addPersonResponse> addPersonAsync(RB90.addPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RB90.authenticateResponse authenticate(RB90.authenticateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/authenticate", ReplyAction="*")]
        System.Threading.Tasks.Task<RB90.authenticateResponse> authenticateAsync(RB90.authenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/searchPerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RB90.searchPersonResponse searchPerson(RB90.searchPersonRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/searchPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<RB90.searchPersonResponse> searchPersonAsync(RB90.searchPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/editPerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RB90.editPersonResponse editPerson(RB90.editPersonRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/editPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<RB90.editPersonResponse> editPersonAsync(RB90.editPersonRequest request);
        
        // CODEGEN: Generating message contract since the operation opstineList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/opstineList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RB90.opstineListResponse opstineList(RB90.opstineListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/opstineList", ReplyAction="*")]
        System.Threading.Tasks.Task<RB90.opstineListResponse> opstineListAsync(RB90.opstineListRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (mjestaListRequest) of message mjestaListRequest does not match the default value (mjestaList)
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/mjestaList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RB90.mjestaListResponse mjestaList(RB90.mjestaListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/mjestaList", ReplyAction="*")]
        System.Threading.Tasks.Task<RB90.mjestaListResponse> mjestaListAsync(RB90.mjestaListRequest request);
        
        // CODEGEN: Generating message contract since the operation javneIspraveList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/javneIspraveList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RB90.javneIspraveListResponse javneIspraveList(RB90.javneIspraveListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/javneIspraveList", ReplyAction="*")]
        System.Threading.Tasks.Task<RB90.javneIspraveListResponse> javneIspraveListAsync(RB90.javneIspraveListRequest request);
        
        // CODEGEN: Generating message contract since the operation tipGostaList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/tipGostaList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RB90.tipGostaListResponse tipGostaList(RB90.tipGostaListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/tipGostaList", ReplyAction="*")]
        System.Threading.Tasks.Task<RB90.tipGostaListResponse> tipGostaListAsync(RB90.tipGostaListRequest request);
        
        // CODEGEN: Generating message contract since the operation drzavaList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/drzavaList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RB90.drzavaListResponse drzavaList(RB90.drzavaListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/drzavaList", ReplyAction="*")]
        System.Threading.Tasks.Task<RB90.drzavaListResponse> drzavaListAsync(RB90.drzavaListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/smjestajniObjektiList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RB90.smjestajniObjektiListResponse smjestajniObjektiList(RB90.smjestajniObjektiListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/smjestajniObjektiList", ReplyAction="*")]
        System.Threading.Tasks.Task<RB90.smjestajniObjektiListResponse> smjestajniObjektiListAsync(RB90.smjestajniObjektiListRequest request);
        
        // CODEGEN: Generating message contract since the operation granicniPrelaziList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/granicniPrelaziList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RB90.granicniPrelaziListResponse granicniPrelaziList(RB90.granicniPrelaziListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/granicniPrelaziList", ReplyAction="*")]
        System.Threading.Tasks.Task<RB90.granicniPrelaziListResponse> granicniPrelaziListAsync(RB90.granicniPrelaziListRequest request);
        
        // CODEGEN: Generating message contract since the operation vrstaVizeList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/vrstaVizeList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RB90.vrstaVizeListResponse vrstaVizeList(RB90.vrstaVizeListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://me.rb90/mup/vrstaVizeList", ReplyAction="*")]
        System.Threading.Tasks.Task<RB90.vrstaVizeListResponse> vrstaVizeListAsync(RB90.vrstaVizeListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://me.rb90/mup/")]
    public partial class stranac
    {
        
        private int idField;
        
        private tipGosta tipGostaField;
        
        private string maticniBrojField;
        
        private string prezimeField;
        
        private string imeField;
        
        private string polField;
        
        private System.DateTime datumRodjenjaField;
        
        private drzava drzavaRodjenjaField;
        
        private string gradRodjenjaField;
        
        private drzava drzavljanstvoField;
        
        private drzava drzavaIzdavanjaDokumentaField;
        
        private javnaIsprava vrstaJavneIspraveField;
        
        private string brojJavneIspraveField;
        
        private string izdavaocJavneIspraveField;
        
        private System.DateTime rokVazenjaIspraveField;
        
        private string vrstaVizeField;
        
        private string brojVizeField;
        
        private string mjestoIzdavanjaVizeField;
        
        private System.DateTime rokVazenjaVizeOdField;
        
        private System.DateTime rokVazenjaVizeDoField;
        
        private System.DateTime datumUlaskaUCGField;
        
        private granicniPrelaz mjestoUlaskaUCGField;
        
        private opstina opstinaBoravkaField;
        
        private mjesto mjestoBoravkaField;
        
        private string adresaBoravkaiKucniBrojField;
        
        private string prezimeKorisnikaObjektaField;
        
        private string imeKorisnikaObjektaField;
        
        private string jmbgKorisnikaObjektaField;
        
        private System.DateTime datumPrijaveField;
        
        private System.DateTime datumOdjaveField;
        
        private drzava drzavaPrebivalistaField;
        
        private string gradPrebivalistaField;
        
        private string adresaiBrojPrebivalistaField;
        
        private smjestajniObjekat davaocSmjestajaField;
        
        private user azuriraoField;
        
        private bool obrisanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tipGosta tipGosta
        {
            get
            {
                return this.tipGostaField;
            }
            set
            {
                this.tipGostaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string maticniBroj
        {
            get
            {
                return this.maticniBrojField;
            }
            set
            {
                this.maticniBrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string prezime
        {
            get
            {
                return this.prezimeField;
            }
            set
            {
                this.prezimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ime
        {
            get
            {
                return this.imeField;
            }
            set
            {
                this.imeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string pol
        {
            get
            {
                return this.polField;
            }
            set
            {
                this.polField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime datumRodjenja
        {
            get
            {
                return this.datumRodjenjaField;
            }
            set
            {
                this.datumRodjenjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public drzava drzavaRodjenja
        {
            get
            {
                return this.drzavaRodjenjaField;
            }
            set
            {
                this.drzavaRodjenjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string gradRodjenja
        {
            get
            {
                return this.gradRodjenjaField;
            }
            set
            {
                this.gradRodjenjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public drzava drzavljanstvo
        {
            get
            {
                return this.drzavljanstvoField;
            }
            set
            {
                this.drzavljanstvoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public drzava drzavaIzdavanjaDokumenta
        {
            get
            {
                return this.drzavaIzdavanjaDokumentaField;
            }
            set
            {
                this.drzavaIzdavanjaDokumentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public javnaIsprava vrstaJavneIsprave
        {
            get
            {
                return this.vrstaJavneIspraveField;
            }
            set
            {
                this.vrstaJavneIspraveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string brojJavneIsprave
        {
            get
            {
                return this.brojJavneIspraveField;
            }
            set
            {
                this.brojJavneIspraveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string izdavaocJavneIsprave
        {
            get
            {
                return this.izdavaocJavneIspraveField;
            }
            set
            {
                this.izdavaocJavneIspraveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public System.DateTime rokVazenjaIsprave
        {
            get
            {
                return this.rokVazenjaIspraveField;
            }
            set
            {
                this.rokVazenjaIspraveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string vrstaVize
        {
            get
            {
                return this.vrstaVizeField;
            }
            set
            {
                this.vrstaVizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string brojVize
        {
            get
            {
                return this.brojVizeField;
            }
            set
            {
                this.brojVizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string mjestoIzdavanjaVize
        {
            get
            {
                return this.mjestoIzdavanjaVizeField;
            }
            set
            {
                this.mjestoIzdavanjaVizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public System.DateTime rokVazenjaVizeOd
        {
            get
            {
                return this.rokVazenjaVizeOdField;
            }
            set
            {
                this.rokVazenjaVizeOdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public System.DateTime rokVazenjaVizeDo
        {
            get
            {
                return this.rokVazenjaVizeDoField;
            }
            set
            {
                this.rokVazenjaVizeDoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public System.DateTime datumUlaskaUCG
        {
            get
            {
                return this.datumUlaskaUCGField;
            }
            set
            {
                this.datumUlaskaUCGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public granicniPrelaz mjestoUlaskaUCG
        {
            get
            {
                return this.mjestoUlaskaUCGField;
            }
            set
            {
                this.mjestoUlaskaUCGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public opstina opstinaBoravka
        {
            get
            {
                return this.opstinaBoravkaField;
            }
            set
            {
                this.opstinaBoravkaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public mjesto mjestoBoravka
        {
            get
            {
                return this.mjestoBoravkaField;
            }
            set
            {
                this.mjestoBoravkaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string adresaBoravkaiKucniBroj
        {
            get
            {
                return this.adresaBoravkaiKucniBrojField;
            }
            set
            {
                this.adresaBoravkaiKucniBrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string prezimeKorisnikaObjekta
        {
            get
            {
                return this.prezimeKorisnikaObjektaField;
            }
            set
            {
                this.prezimeKorisnikaObjektaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string imeKorisnikaObjekta
        {
            get
            {
                return this.imeKorisnikaObjektaField;
            }
            set
            {
                this.imeKorisnikaObjektaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string jmbgKorisnikaObjekta
        {
            get
            {
                return this.jmbgKorisnikaObjektaField;
            }
            set
            {
                this.jmbgKorisnikaObjektaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public System.DateTime datumPrijave
        {
            get
            {
                return this.datumPrijaveField;
            }
            set
            {
                this.datumPrijaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public System.DateTime datumOdjave
        {
            get
            {
                return this.datumOdjaveField;
            }
            set
            {
                this.datumOdjaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public drzava drzavaPrebivalista
        {
            get
            {
                return this.drzavaPrebivalistaField;
            }
            set
            {
                this.drzavaPrebivalistaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string gradPrebivalista
        {
            get
            {
                return this.gradPrebivalistaField;
            }
            set
            {
                this.gradPrebivalistaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string adresaiBrojPrebivalista
        {
            get
            {
                return this.adresaiBrojPrebivalistaField;
            }
            set
            {
                this.adresaiBrojPrebivalistaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public smjestajniObjekat davaocSmjestaja
        {
            get
            {
                return this.davaocSmjestajaField;
            }
            set
            {
                this.davaocSmjestajaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public user azurirao
        {
            get
            {
                return this.azuriraoField;
            }
            set
            {
                this.azuriraoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public bool obrisan
        {
            get
            {
                return this.obrisanField;
            }
            set
            {
                this.obrisanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://me.rb90/mup/")]
    public partial class tipGosta
    {
        
        private int idField;
        
        private string nazivField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string naziv
        {
            get
            {
                return this.nazivField;
            }
            set
            {
                this.nazivField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://me.rb90/mup/")]
    public partial class searchPersonParams
    {
        
        private string imeField;
        
        private string prezimeField;
        
        private int tipDokumentaField;
        
        private string brojDokumentaField;
        
        private string drzavaIzdavanjaDokumentaField;
        
        private System.DateTime datumOdField;
        
        private System.DateTime datumDoField;
        
        private int smjestajniObjekatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ime
        {
            get
            {
                return this.imeField;
            }
            set
            {
                this.imeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string prezime
        {
            get
            {
                return this.prezimeField;
            }
            set
            {
                this.prezimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int tipDokumenta
        {
            get
            {
                return this.tipDokumentaField;
            }
            set
            {
                this.tipDokumentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string brojDokumenta
        {
            get
            {
                return this.brojDokumentaField;
            }
            set
            {
                this.brojDokumentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string drzavaIzdavanjaDokumenta
        {
            get
            {
                return this.drzavaIzdavanjaDokumentaField;
            }
            set
            {
                this.drzavaIzdavanjaDokumentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime datumOd
        {
            get
            {
                return this.datumOdField;
            }
            set
            {
                this.datumOdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime datumDo
        {
            get
            {
                return this.datumDoField;
            }
            set
            {
                this.datumDoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int smjestajniObjekat
        {
            get
            {
                return this.smjestajniObjekatField;
            }
            set
            {
                this.smjestajniObjekatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://me.rb90/mup/")]
    public partial class user
    {
        
        private int idField;
        
        private string imePrezimeField;
        
        private int idUlogeField;
        
        private string nazivUlogeField;
        
        private opstina opstinaTuristickeOrganizacijeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string imePrezime
        {
            get
            {
                return this.imePrezimeField;
            }
            set
            {
                this.imePrezimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idUloge
        {
            get
            {
                return this.idUlogeField;
            }
            set
            {
                this.idUlogeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nazivUloge
        {
            get
            {
                return this.nazivUlogeField;
            }
            set
            {
                this.nazivUlogeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public opstina opstinaTuristickeOrganizacije
        {
            get
            {
                return this.opstinaTuristickeOrganizacijeField;
            }
            set
            {
                this.opstinaTuristickeOrganizacijeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://me.rb90/mup/")]
    public partial class opstina
    {
        
        private string kodField;
        
        private string nazivField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string naziv
        {
            get
            {
                return this.nazivField;
            }
            set
            {
                this.nazivField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://me.rb90/mup/")]
    public partial class smjestajniObjekat
    {
        
        private int idField;
        
        private string nazivField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string naziv
        {
            get
            {
                return this.nazivField;
            }
            set
            {
                this.nazivField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://me.rb90/mup/")]
    public partial class mjesto
    {
        
        private string kodField;
        
        private string nazivField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string naziv
        {
            get
            {
                return this.nazivField;
            }
            set
            {
                this.nazivField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://me.rb90/mup/")]
    public partial class granicniPrelaz
    {
        
        private int idField;
        
        private string nazivField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string naziv
        {
            get
            {
                return this.nazivField;
            }
            set
            {
                this.nazivField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://me.rb90/mup/")]
    public partial class javnaIsprava
    {
        
        private int idField;
        
        private string nazivField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string naziv
        {
            get
            {
                return this.nazivField;
            }
            set
            {
                this.nazivField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://me.rb90/mup/")]
    public partial class drzava
    {
        
        private string kodField;
        
        private string nazivField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string naziv
        {
            get
            {
                return this.nazivField;
            }
            set
            {
                this.nazivField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addPersonRequest", WrapperNamespace="http://me.rb90/mup/", IsWrapped=true)]
    public partial class addPersonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RB90.stranac stranac;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int azurirao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string potpisani_zahtjev;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string podaci;
        
        public addPersonRequest()
        {
        }
        
        public addPersonRequest(RB90.stranac stranac, int azurirao, string potpisani_zahtjev, string podaci)
        {
            this.stranac = stranac;
            this.azurirao = azurirao;
            this.potpisani_zahtjev = potpisani_zahtjev;
            this.podaci = podaci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addPersonResponse", WrapperNamespace="http://me.rb90/mup/", IsWrapped=true)]
    public partial class addPersonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public addPersonResponse()
        {
        }
        
        public addPersonResponse(string result, int id)
        {
            this.result = result;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticateRequest", WrapperNamespace="http://me.rb90/mup/", IsWrapped=true)]
    public partial class authenticateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serijskiBrojSertifikata;
        
        public authenticateRequest()
        {
        }
        
        public authenticateRequest(string serijskiBrojSertifikata)
        {
            this.serijskiBrojSertifikata = serijskiBrojSertifikata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticateResponse", WrapperNamespace="http://me.rb90/mup/", IsWrapped=true)]
    public partial class authenticateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RB90.user user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("listaSmjestajnihObjekata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RB90.smjestajniObjekat[] listaSmjestajnihObjekata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result;
        
        public authenticateResponse()
        {
        }
        
        public authenticateResponse(RB90.user user, RB90.smjestajniObjekat[] listaSmjestajnihObjekata, string result)
        {
            this.user = user;
            this.listaSmjestajnihObjekata = listaSmjestajnihObjekata;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchPersonRequest", WrapperNamespace="http://me.rb90/mup/", IsWrapped=true)]
    public partial class searchPersonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RB90.searchPersonParams searchRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string potpisani_zahtjev;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string podaci;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int korisnik_id;
        
        public searchPersonRequest()
        {
        }
        
        public searchPersonRequest(RB90.searchPersonParams searchRequest, string potpisani_zahtjev, string podaci, int korisnik_id)
        {
            this.searchRequest = searchRequest;
            this.potpisani_zahtjev = potpisani_zahtjev;
            this.podaci = podaci;
            this.korisnik_id = korisnik_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchPersonResponse", WrapperNamespace="http://me.rb90/mup/", IsWrapped=true)]
    public partial class searchPersonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("listPerson", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RB90.stranac[] listPerson;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result;
        
        public searchPersonResponse()
        {
        }
        
        public searchPersonResponse(RB90.stranac[] listPerson, string result)
        {
            this.listPerson = listPerson;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editPersonRequest", WrapperNamespace="http://me.rb90/mup/", IsWrapped=true)]
    public partial class editPersonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RB90.stranac stranac;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int azurirao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string potpisani_zahtjev;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string podaci;
        
        public editPersonRequest()
        {
        }
        
        public editPersonRequest(RB90.stranac stranac, int azurirao, string potpisani_zahtjev, string podaci)
        {
            this.stranac = stranac;
            this.azurirao = azurirao;
            this.potpisani_zahtjev = potpisani_zahtjev;
            this.podaci = podaci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editPersonResponse", WrapperNamespace="http://me.rb90/mup/", IsWrapped=true)]
    public partial class editPersonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public editPersonResponse()
        {
        }
        
        public editPersonResponse(string result, int id)
        {
            this.result = result;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class opstineListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="opstineListRequest", Namespace="http://me.rb90/mup/", Order=0)]
        public object opstineListRequest1;
        
        public opstineListRequest()
        {
        }
        
        public opstineListRequest(object opstineListRequest1)
        {
            this.opstineListRequest1 = opstineListRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class opstineListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="opstineListResponse", Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("opstine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RB90.opstina[] opstineListResponse1;
        
        public opstineListResponse()
        {
        }
        
        public opstineListResponse(RB90.opstina[] opstineListResponse1)
        {
            this.opstineListResponse1 = opstineListResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mjestaListRequest", WrapperNamespace="http://me.rb90/mup/", IsWrapped=true)]
    public partial class mjestaListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RB90.opstina opstina;
        
        public mjestaListRequest()
        {
        }
        
        public mjestaListRequest(RB90.opstina opstina)
        {
            this.opstina = opstina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mjestaListResponse", WrapperNamespace="http://me.rb90/mup/", IsWrapped=true)]
    public partial class mjestaListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mjesta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RB90.mjesto[] mjesta;
        
        public mjestaListResponse()
        {
        }
        
        public mjestaListResponse(RB90.mjesto[] mjesta)
        {
            this.mjesta = mjesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class javneIspraveListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="javneIspraveListRequest", Namespace="http://me.rb90/mup/", Order=0)]
        public object javneIspraveListRequest1;
        
        public javneIspraveListRequest()
        {
        }
        
        public javneIspraveListRequest(object javneIspraveListRequest1)
        {
            this.javneIspraveListRequest1 = javneIspraveListRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class javneIspraveListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="javneIspraveListResponse", Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("javneIsprave", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RB90.javnaIsprava[] javneIspraveListResponse1;
        
        public javneIspraveListResponse()
        {
        }
        
        public javneIspraveListResponse(RB90.javnaIsprava[] javneIspraveListResponse1)
        {
            this.javneIspraveListResponse1 = javneIspraveListResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class tipGostaListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="tipGostaListRequest", Namespace="http://me.rb90/mup/", Order=0)]
        public object tipGostaListRequest1;
        
        public tipGostaListRequest()
        {
        }
        
        public tipGostaListRequest(object tipGostaListRequest1)
        {
            this.tipGostaListRequest1 = tipGostaListRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class tipGostaListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="tipGostaListResponse", Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tipGostaList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RB90.tipGosta[] tipGostaListResponse1;
        
        public tipGostaListResponse()
        {
        }
        
        public tipGostaListResponse(RB90.tipGosta[] tipGostaListResponse1)
        {
            this.tipGostaListResponse1 = tipGostaListResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class drzavaListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="drzavaListRequest", Namespace="http://me.rb90/mup/", Order=0)]
        public object drzavaListRequest1;
        
        public drzavaListRequest()
        {
        }
        
        public drzavaListRequest(object drzavaListRequest1)
        {
            this.drzavaListRequest1 = drzavaListRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class drzavaListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="drzavaListResponse", Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("drzaveList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RB90.drzava[] drzavaListResponse1;
        
        public drzavaListResponse()
        {
        }
        
        public drzavaListResponse(RB90.drzava[] drzavaListResponse1)
        {
            this.drzavaListResponse1 = drzavaListResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smjestajniObjektiListRequest", WrapperNamespace="http://me.rb90/mup/", IsWrapped=true)]
    public partial class smjestajniObjektiListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kodOpstine;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int korisnik_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string potpisani_zahtjev;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string podaci;
        
        public smjestajniObjektiListRequest()
        {
        }
        
        public smjestajniObjektiListRequest(string kodOpstine, int korisnik_id, string potpisani_zahtjev, string podaci)
        {
            this.kodOpstine = kodOpstine;
            this.korisnik_id = korisnik_id;
            this.potpisani_zahtjev = potpisani_zahtjev;
            this.podaci = podaci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smjestajniObjektiListResponse", WrapperNamespace="http://me.rb90/mup/", IsWrapped=true)]
    public partial class smjestajniObjektiListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://me.rb90/mup/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("listaObjekata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RB90.smjestajniObjekat[] listaObjekata;
        
        public smjestajniObjektiListResponse()
        {
        }
        
        public smjestajniObjektiListResponse(string result, RB90.smjestajniObjekat[] listaObjekata)
        {
            this.result = result;
            this.listaObjekata = listaObjekata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class granicniPrelaziListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="granicniPrelaziListRequest", Namespace="http://me.rb90/mup/", Order=0)]
        public object granicniPrelaziListRequest1;
        
        public granicniPrelaziListRequest()
        {
        }
        
        public granicniPrelaziListRequest(object granicniPrelaziListRequest1)
        {
            this.granicniPrelaziListRequest1 = granicniPrelaziListRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class granicniPrelaziListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="granicniPrelaziListResponse", Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("listaGP", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RB90.granicniPrelaz[] granicniPrelaziListResponse1;
        
        public granicniPrelaziListResponse()
        {
        }
        
        public granicniPrelaziListResponse(RB90.granicniPrelaz[] granicniPrelaziListResponse1)
        {
            this.granicniPrelaziListResponse1 = granicniPrelaziListResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vrstaVizeListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="vrstaVizeListRequest", Namespace="http://me.rb90/mup/", Order=0)]
        public object vrstaVizeListRequest1;
        
        public vrstaVizeListRequest()
        {
        }
        
        public vrstaVizeListRequest(object vrstaVizeListRequest1)
        {
            this.vrstaVizeListRequest1 = vrstaVizeListRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vrstaVizeListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="vrstaVizeListResponse", Namespace="http://me.rb90/mup/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("listaVrsta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] vrstaVizeListResponse1;
        
        public vrstaVizeListResponse()
        {
        }
        
        public vrstaVizeListResponse(string[] vrstaVizeListResponse1)
        {
            this.vrstaVizeListResponse1 = vrstaVizeListResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface mupChannel : RB90.mup, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class mupClient : System.ServiceModel.ClientBase<RB90.mup>, RB90.mup
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public mupClient() : 
                base(mupClient.GetDefaultBinding(), mupClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.mupSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public mupClient(EndpointConfiguration endpointConfiguration) : 
                base(mupClient.GetBindingForEndpoint(endpointConfiguration), mupClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public mupClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(mupClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public mupClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(mupClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public mupClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RB90.addPersonResponse RB90.mup.addPerson(RB90.addPersonRequest request)
        {
            return base.Channel.addPerson(request);
        }
        
        public string addPerson(RB90.stranac stranac, int azurirao, string potpisani_zahtjev, string podaci, out int id)
        {
            RB90.addPersonRequest inValue = new RB90.addPersonRequest();
            inValue.stranac = stranac;
            inValue.azurirao = azurirao;
            inValue.potpisani_zahtjev = potpisani_zahtjev;
            inValue.podaci = podaci;
            RB90.addPersonResponse retVal = ((RB90.mup)(this)).addPerson(inValue);
            id = retVal.id;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<RB90.addPersonResponse> addPersonAsync(RB90.addPersonRequest request)
        {
            return base.Channel.addPersonAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RB90.authenticateResponse RB90.mup.authenticate(RB90.authenticateRequest request)
        {
            return base.Channel.authenticate(request);
        }
        
        public RB90.user authenticate(string serijskiBrojSertifikata, out RB90.smjestajniObjekat[] listaSmjestajnihObjekata, out string result)
        {
            RB90.authenticateRequest inValue = new RB90.authenticateRequest();
            inValue.serijskiBrojSertifikata = serijskiBrojSertifikata;
            RB90.authenticateResponse retVal = ((RB90.mup)(this)).authenticate(inValue);
            listaSmjestajnihObjekata = retVal.listaSmjestajnihObjekata;
            result = retVal.result;
            return retVal.user;
        }
        
        public System.Threading.Tasks.Task<RB90.authenticateResponse> authenticateAsync(RB90.authenticateRequest request)
        {
            return base.Channel.authenticateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RB90.searchPersonResponse RB90.mup.searchPerson(RB90.searchPersonRequest request)
        {
            return base.Channel.searchPerson(request);
        }
        
        public RB90.stranac[] searchPerson(RB90.searchPersonParams searchRequest, string potpisani_zahtjev, string podaci, int korisnik_id, out string result)
        {
            RB90.searchPersonRequest inValue = new RB90.searchPersonRequest();
            inValue.searchRequest = searchRequest;
            inValue.potpisani_zahtjev = potpisani_zahtjev;
            inValue.podaci = podaci;
            inValue.korisnik_id = korisnik_id;
            RB90.searchPersonResponse retVal = ((RB90.mup)(this)).searchPerson(inValue);
            result = retVal.result;
            return retVal.listPerson;
        }
        
        public System.Threading.Tasks.Task<RB90.searchPersonResponse> searchPersonAsync(RB90.searchPersonRequest request)
        {
            return base.Channel.searchPersonAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RB90.editPersonResponse RB90.mup.editPerson(RB90.editPersonRequest request)
        {
            return base.Channel.editPerson(request);
        }
        
        public string editPerson(RB90.stranac stranac, int azurirao, string potpisani_zahtjev, string podaci, out int id)
        {
            RB90.editPersonRequest inValue = new RB90.editPersonRequest();
            inValue.stranac = stranac;
            inValue.azurirao = azurirao;
            inValue.potpisani_zahtjev = potpisani_zahtjev;
            inValue.podaci = podaci;
            RB90.editPersonResponse retVal = ((RB90.mup)(this)).editPerson(inValue);
            id = retVal.id;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<RB90.editPersonResponse> editPersonAsync(RB90.editPersonRequest request)
        {
            return base.Channel.editPersonAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RB90.opstineListResponse RB90.mup.opstineList(RB90.opstineListRequest request)
        {
            return base.Channel.opstineList(request);
        }
        
        public RB90.opstina[] opstineList(object opstineListRequest1)
        {
            RB90.opstineListRequest inValue = new RB90.opstineListRequest();
            inValue.opstineListRequest1 = opstineListRequest1;
            RB90.opstineListResponse retVal = ((RB90.mup)(this)).opstineList(inValue);
            return retVal.opstineListResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RB90.opstineListResponse> RB90.mup.opstineListAsync(RB90.opstineListRequest request)
        {
            return base.Channel.opstineListAsync(request);
        }
        
        public System.Threading.Tasks.Task<RB90.opstineListResponse> opstineListAsync(object opstineListRequest1)
        {
            RB90.opstineListRequest inValue = new RB90.opstineListRequest();
            inValue.opstineListRequest1 = opstineListRequest1;
            return ((RB90.mup)(this)).opstineListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RB90.mjestaListResponse RB90.mup.mjestaList(RB90.mjestaListRequest request)
        {
            return base.Channel.mjestaList(request);
        }
        
        public RB90.mjesto[] mjestaList(RB90.opstina opstina)
        {
            RB90.mjestaListRequest inValue = new RB90.mjestaListRequest();
            inValue.opstina = opstina;
            RB90.mjestaListResponse retVal = ((RB90.mup)(this)).mjestaList(inValue);
            return retVal.mjesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RB90.mjestaListResponse> RB90.mup.mjestaListAsync(RB90.mjestaListRequest request)
        {
            return base.Channel.mjestaListAsync(request);
        }
        
        public System.Threading.Tasks.Task<RB90.mjestaListResponse> mjestaListAsync(RB90.opstina opstina)
        {
            RB90.mjestaListRequest inValue = new RB90.mjestaListRequest();
            inValue.opstina = opstina;
            return ((RB90.mup)(this)).mjestaListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RB90.javneIspraveListResponse RB90.mup.javneIspraveList(RB90.javneIspraveListRequest request)
        {
            return base.Channel.javneIspraveList(request);
        }
        
        public RB90.javnaIsprava[] javneIspraveList(object javneIspraveListRequest1)
        {
            RB90.javneIspraveListRequest inValue = new RB90.javneIspraveListRequest();
            inValue.javneIspraveListRequest1 = javneIspraveListRequest1;
            RB90.javneIspraveListResponse retVal = ((RB90.mup)(this)).javneIspraveList(inValue);
            return retVal.javneIspraveListResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RB90.javneIspraveListResponse> RB90.mup.javneIspraveListAsync(RB90.javneIspraveListRequest request)
        {
            return base.Channel.javneIspraveListAsync(request);
        }
        
        public System.Threading.Tasks.Task<RB90.javneIspraveListResponse> javneIspraveListAsync(object javneIspraveListRequest1)
        {
            RB90.javneIspraveListRequest inValue = new RB90.javneIspraveListRequest();
            inValue.javneIspraveListRequest1 = javneIspraveListRequest1;
            return ((RB90.mup)(this)).javneIspraveListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RB90.tipGostaListResponse RB90.mup.tipGostaList(RB90.tipGostaListRequest request)
        {
            return base.Channel.tipGostaList(request);
        }
        
        public RB90.tipGosta[] tipGostaList(object tipGostaListRequest1)
        {
            RB90.tipGostaListRequest inValue = new RB90.tipGostaListRequest();
            inValue.tipGostaListRequest1 = tipGostaListRequest1;
            RB90.tipGostaListResponse retVal = ((RB90.mup)(this)).tipGostaList(inValue);
            return retVal.tipGostaListResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RB90.tipGostaListResponse> RB90.mup.tipGostaListAsync(RB90.tipGostaListRequest request)
        {
            return base.Channel.tipGostaListAsync(request);
        }
        
        public System.Threading.Tasks.Task<RB90.tipGostaListResponse> tipGostaListAsync(object tipGostaListRequest1)
        {
            RB90.tipGostaListRequest inValue = new RB90.tipGostaListRequest();
            inValue.tipGostaListRequest1 = tipGostaListRequest1;
            return ((RB90.mup)(this)).tipGostaListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RB90.drzavaListResponse RB90.mup.drzavaList(RB90.drzavaListRequest request)
        {
            return base.Channel.drzavaList(request);
        }
        
        public RB90.drzava[] drzavaList(object drzavaListRequest1)
        {
            RB90.drzavaListRequest inValue = new RB90.drzavaListRequest();
            inValue.drzavaListRequest1 = drzavaListRequest1;
            RB90.drzavaListResponse retVal = ((RB90.mup)(this)).drzavaList(inValue);
            return retVal.drzavaListResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RB90.drzavaListResponse> RB90.mup.drzavaListAsync(RB90.drzavaListRequest request)
        {
            return base.Channel.drzavaListAsync(request);
        }
        
        public System.Threading.Tasks.Task<RB90.drzavaListResponse> drzavaListAsync(object drzavaListRequest1)
        {
            RB90.drzavaListRequest inValue = new RB90.drzavaListRequest();
            inValue.drzavaListRequest1 = drzavaListRequest1;
            return ((RB90.mup)(this)).drzavaListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RB90.smjestajniObjektiListResponse RB90.mup.smjestajniObjektiList(RB90.smjestajniObjektiListRequest request)
        {
            return base.Channel.smjestajniObjektiList(request);
        }
        
        public string smjestajniObjektiList(string kodOpstine, int korisnik_id, string potpisani_zahtjev, string podaci, out RB90.smjestajniObjekat[] listaObjekata)
        {
            RB90.smjestajniObjektiListRequest inValue = new RB90.smjestajniObjektiListRequest();
            inValue.kodOpstine = kodOpstine;
            inValue.korisnik_id = korisnik_id;
            inValue.potpisani_zahtjev = potpisani_zahtjev;
            inValue.podaci = podaci;
            RB90.smjestajniObjektiListResponse retVal = ((RB90.mup)(this)).smjestajniObjektiList(inValue);
            listaObjekata = retVal.listaObjekata;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<RB90.smjestajniObjektiListResponse> smjestajniObjektiListAsync(RB90.smjestajniObjektiListRequest request)
        {
            return base.Channel.smjestajniObjektiListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RB90.granicniPrelaziListResponse RB90.mup.granicniPrelaziList(RB90.granicniPrelaziListRequest request)
        {
            return base.Channel.granicniPrelaziList(request);
        }
        
        public RB90.granicniPrelaz[] granicniPrelaziList(object granicniPrelaziListRequest1)
        {
            RB90.granicniPrelaziListRequest inValue = new RB90.granicniPrelaziListRequest();
            inValue.granicniPrelaziListRequest1 = granicniPrelaziListRequest1;
            RB90.granicniPrelaziListResponse retVal = ((RB90.mup)(this)).granicniPrelaziList(inValue);
            return retVal.granicniPrelaziListResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RB90.granicniPrelaziListResponse> RB90.mup.granicniPrelaziListAsync(RB90.granicniPrelaziListRequest request)
        {
            return base.Channel.granicniPrelaziListAsync(request);
        }
        
        public System.Threading.Tasks.Task<RB90.granicniPrelaziListResponse> granicniPrelaziListAsync(object granicniPrelaziListRequest1)
        {
            RB90.granicniPrelaziListRequest inValue = new RB90.granicniPrelaziListRequest();
            inValue.granicniPrelaziListRequest1 = granicniPrelaziListRequest1;
            return ((RB90.mup)(this)).granicniPrelaziListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RB90.vrstaVizeListResponse RB90.mup.vrstaVizeList(RB90.vrstaVizeListRequest request)
        {
            return base.Channel.vrstaVizeList(request);
        }
        
        public string[] vrstaVizeList(object vrstaVizeListRequest1)
        {
            RB90.vrstaVizeListRequest inValue = new RB90.vrstaVizeListRequest();
            inValue.vrstaVizeListRequest1 = vrstaVizeListRequest1;
            RB90.vrstaVizeListResponse retVal = ((RB90.mup)(this)).vrstaVizeList(inValue);
            return retVal.vrstaVizeListResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RB90.vrstaVizeListResponse> RB90.mup.vrstaVizeListAsync(RB90.vrstaVizeListRequest request)
        {
            return base.Channel.vrstaVizeListAsync(request);
        }
        
        public System.Threading.Tasks.Task<RB90.vrstaVizeListResponse> vrstaVizeListAsync(object vrstaVizeListRequest1)
        {
            RB90.vrstaVizeListRequest inValue = new RB90.vrstaVizeListRequest();
            inValue.vrstaVizeListRequest1 = vrstaVizeListRequest1;
            return ((RB90.mup)(this)).vrstaVizeListAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.mupSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.mupSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://rb90.dokumenta.me/publicws/mup/MupImpl");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return mupClient.GetBindingForEndpoint(EndpointConfiguration.mupSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return mupClient.GetEndpointAddress(EndpointConfiguration.mupSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            mupSOAP,
        }
    }
}
